---
layout:     post   				    # 使用的布局（不需要改）
title:      Promise 				# 标题 
subtitle:   #副标题
date:       2022-03-14 				# 时间
author:     HaxW 						# 作者
header-img: img/post-bg-2015.jpg 	#这篇文章标题背景图片
catalog: true 						# 是否归档
tags:								#标签
    - JavaScript
---

参考博文：  
 [当面试官问你Promise的时候，他究竟想听到什么？](https://zhuanlan.zhihu.com/p/29235579)  
 [前端面试之JavaScript篇](https://www.yuque.com/cuggz/interview/vgbphi#791da1512b169c29fd50646942ee7e48)  
[千古前端图文教程-Promise入门详解](https://web.qianguyihao.com/06-JavaScript%E5%9F%BA%E7%A1%80%EF%BC%9A%E5%BC%82%E6%AD%A5%E7%BC%96%E7%A8%8B/05-Promise%E5%85%A5%E9%97%A8%E8%AF%A6%E8%A7%A3.html)
### 它是啥？
一个容器，里面保存着某个未来才会结束的事件的结果。
一个对象，有三个状态——`pending`、`fulfilled`、`rejected`，且状态一旦改变后就不能再变。
### 干什么？
解决传统回调方式的问题（过早/过晚/过多/过少/回调地狱/...）
### 怎么写？
```
let promise = new Promise((resolve,reject) => {
    //刚进来，promise的状态为pending，且为同步状态
    //此处开始写异步代码，如setTimeout
    if(异步请求成功){
        resolve(successMsg);//promise的状态被改为fulfilled
    }
    else{
        reject(errorMsg);//promise的状态被改为rejected
    }
    //这里又可以执行同步任务，比如console.log()
})

promise.then(//then的括号里有两个参数，这两个参数都是函数，作用分别是处理上面的resolve()和reject()传来的信息；至少要有resolve()执行了才能走到.then()
    (successMsg) => {//如果promise的状态为fulfilled
        console.log(successMsg);
    },
    (errorMsg) => {//如果promise的状态为rejected
        console.log(errorMsg);
    }
)

//或者：
promise.then(
    (successMsg) => {
        console.log(successMsg);
    }
)
.catch(
    (errorMsg) => {
        console.log(errorMsg);
    }
)
//也就是说想要捕获并处理promise的reject状态，可以给then传递两个参数，也可以在.then()后面用catch捕获；但不能直接用try...catch...，因为这种方法只能捕获同步里的异常。
```
其中`resolve()`、`reject()`两个方法可以静态调用，返回值都是`Promise`对象。写法如下：
```
Promise.resolve("解决了！").then((Msg) => {console.log(Msg)})；//输出结果为 解决了！
Promise.reject("失败了！").catch((Msg) => {console.log(Msg)}); //输出结果为 失败了！
```
### 常用方法
##### Promise.then()
上面讲过了，总之就记住一点：返回值是一个新的`Promise`对象
##### Promise.catch()
同理，作用是处理`rejected`状态的`Promise`，等价于用`then()`的第二个参数；返回值同样也是`Promise`对象。 
当然用`catch()`也可以用于处理在执行`resolve()`时发生的异常。
##### Promise.all()
`Promise.all()`的参数是一个数组，里面放着多个`Promise`对象。它用于并发处理多个异步任务，所有任务都执行成功，才算成功，并返回一个数组，和之前传入的参数数组的`resolve`值一一对应；只要有一个失败，就会马上走到`reject`，整体都算失败。  
```
let promise1 = new Promise((resolve,reject)=>{
    setTimeout(()=>{
        console.log(1);
        resolve(1);
    },2000)
});
let promise2 = new Promise((resolve,reject)=>{
    setTimeout(()=>{
        console.log(2);
        resolve(2);
    },1000)
});
let promise3 = new Promise((resolve,reject)=>{
	setTimeout(()=>{
        console.log(3);
        resolve(3);
	},3000)
});
Promise.all([promise1,promise2,promise3]).then(res=>{
    console.log(res);
})
//这段代码的输出结果为：（等一秒）→2→（等一秒）→1→（等一秒）→3→ [1,2,3]，注意最后的数组和前面一个3几乎同时输出
```
如果传递空数组，会立即决议，决议结果是`fulfilled`，值是`undefined`。
##### Promise.race()
和`Promise.all()`类似，传入参数也是一个`Promise`数组，但它返回的是第一个**执行完成**的 `Promise`，且状态和第一个完成的任务状态保持一致。  
```
let promise1 = new Promise((resolve,reject)=>{
	setTimeout(()=>{
        console.log(1);
        reject(1);
	},2000)
});
let promise2 = new Promise((resolve,reject)=>{
	setTimeout(()=>{
        console.log(2);
        resolve(2);
	},1000)
});
let promise3 = new Promise((resolve,reject)=>{
	setTimeout(()=>{
        console.log(3);
        resolve(3);
	},3000)
});
Promise.race([promise1,promise2,promise3]).then(res=>{
	console.log(res);
	//结果：2
},rej=>{
    console.log(rej);
} //走不到这里，没有输出
)
//这段代码的输出结果为：（等一秒）→2→2→（等一秒）→1→（等一秒）→3
```
如果传递空数组，会永远不决议，程序卡死。
这个方法有个用处：当某件事超过一段时间后可以让它直接停掉。但要注意这种方法并不能用于停止`setInterval()`的计时器，可以看看[这个例子](https://blog.csdn.net/star094606/article/details/94735215)，可以看到输出结束后程序仍然在运行，计时器并未停止。
##### Promise.finally()
指的是不管`Promise`对象最后的状态如何，都会执行的操作。
### async和await
可以把这两个东西看作一种特殊的“运算符”，是为了优化`.then()`链才开发出来的。
##### 用法
###### async
写在函数前，作用是申明“这个函数是异步的”。
```
async function testAsy(){
   return 'hello world';
}
let result = testAsy(); 
console.log(result)
```
`async`函数返回的是一个**Promise对象**，也就是说会用`Promise.resolve()`把返回值封装。上面的`testAsy()`等价于：
```
function testAsy(){
    return Promise.resolve('hello world');
}
```
如果一个函数没有返回值，在它前面加上`async`，则会返回`Promise.resolve(undefined)`。
###### await
表示的是“我要等后面的东西”，而等待的东西既可以是`Promise`对象也可以是别的。 
如果等的不是`Promise`对象：那这个`await`等于不加； 
如果等的是`Promise`对象：`await`会阻塞后面的代码，等待`Promise`对象`resolve()`，之后把`resolve`的值作为表达式的运算结果。
```
function testAsy(x){
   return new Promise(resolve=>{setTimeout(() => {
       resolve(x);
     }, 3000)
    }
   )
}
async function testAwt(){    
  let result =  await testAsy('hello world');
  console.log(result);    // 3秒钟之后出现hello world
  console.log('cuger')   // 3秒钟之后出现cug
}
testAwt();
console.log('cug')  //立即输出cug
```
这个例子中，输出结果应是cug→（等待三秒钟）→输出hello world→输出cuger。  
如果把`testAsy("hello world")`前的`await`拿掉，则会几乎同时输出Promise、cuger、cug，之后等待3秒后程序结束。
注意**await一定要用在async函数里**。
##### 捕获异常
```
async function fn(){
    try{
        let a = await Promise.reject('error')
    }catch(error){
        console.log(error)
    }
}
```
